"""add_dead_app_reports

Revision ID: 3169e8bfb108
Revises: 22e5cc781c14
Create Date: 2026-01-04 19:21:56.361457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3169e8bfb108'
down_revision: Union[str, Sequence[str], None] = '22e5cc781c14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dead_app_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'DISMISSED', name='reportstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dead_app_reports_app_id'), 'dead_app_reports', ['app_id'], unique=False)
    op.create_index(op.f('ix_dead_app_reports_id'), 'dead_app_reports', ['id'], unique=False)
    op.create_index(op.f('ix_dead_app_reports_reporter_id'), 'dead_app_reports', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_dead_app_reports_status'), 'dead_app_reports', ['status'], unique=False)
    op.add_column('apps', sa.Column('is_dead', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.create_index(op.f('ix_apps_is_dead'), 'apps', ['is_dead'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apps_is_dead'), table_name='apps')
    op.drop_column('apps', 'is_dead')
    op.drop_index(op.f('ix_dead_app_reports_status'), table_name='dead_app_reports')
    op.drop_index(op.f('ix_dead_app_reports_reporter_id'), table_name='dead_app_reports')
    op.drop_index(op.f('ix_dead_app_reports_id'), table_name='dead_app_reports')
    op.drop_index(op.f('ix_dead_app_reports_app_id'), table_name='dead_app_reports')
    op.drop_table('dead_app_reports')
    # ### end Alembic commands ###
