"""add_dream_ownership

Revision ID: 856621699de9
Revises: 8f5f7b26c393
Create Date: 2026-01-02 11:34:52.270573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '856621699de9'
down_revision: Union[str, Sequence[str], None] = '8f5f7b26c393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Manual enum update (idempotent)
    op.execute("""
    DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_enum e ON t.oid = e.enumtypid WHERE t.typname = 'notificationtype' AND e.enumlabel = 'OWNERSHIP_CLAIM') THEN
            ALTER TYPE notificationtype ADD VALUE 'OWNERSHIP_CLAIM';
        END IF;
    END
    $$;
    """)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ownership_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dream_id', sa.Integer(), nullable=False),
    sa.Column('claimant_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='claimstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['claimant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dream_id'], ['dreams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ownership_claims_claimant_id'), 'ownership_claims', ['claimant_id'], unique=False)
    op.create_index(op.f('ix_ownership_claims_dream_id'), 'ownership_claims', ['dream_id'], unique=False)
    op.create_index(op.f('ix_ownership_claims_id'), 'ownership_claims', ['id'], unique=False)
    op.add_column('dreams', sa.Column('is_owner', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index(op.f('ix_dreams_is_owner'), 'dreams', ['is_owner'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dreams_is_owner'), table_name='dreams')
    op.drop_column('dreams', 'is_owner')
    op.drop_index(op.f('ix_ownership_claims_id'), table_name='ownership_claims')
    op.drop_index(op.f('ix_ownership_claims_dream_id'), table_name='ownership_claims')
    op.drop_index(op.f('ix_ownership_claims_claimant_id'), table_name='ownership_claims')
    op.drop_table('ownership_claims')
    # ### end Alembic commands ###
