"""add dreamware v2 fields

Revision ID: 8f6f1cff722a
Revises: 0922b5a93c22
Create Date: 2025-12-28 23:27:18.631235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f6f1cff722a'
down_revision: Union[str, Sequence[str], None] = '0922b5a93c22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dreams', sa.Column('app_url', sa.String(length=512), nullable=True))
    op.add_column('dreams', sa.Column('is_agent_submitted', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('api_key', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_api_key'), 'users', ['api_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_api_key'), table_name='users')
    op.drop_column('users', 'api_key')
    op.drop_column('dreams', 'is_agent_submitted')
    op.drop_column('dreams', 'app_url')
    # ### end Alembic commands ###
