"""add_is_admin_to_users

Revision ID: f920d2c1e981
Revises: 856621699de9
Create Date: 2026-01-02 17:37:17.178791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f920d2c1e981'
down_revision: Union[str, Sequence[str], None] = '856621699de9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column as nullable first
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    
    # Update existing rows to False
    op.execute("UPDATE users SET is_admin = False")
    
    # Set to NOT NULL
    op.alter_column('users', 'is_admin', nullable=False)
    
    op.create_index(op.f('ix_users_is_admin'), 'users', ['is_admin'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_is_admin'), table_name='users')
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
